#!/usr/bin/Rscript
##
usage = function() {
    cat('
makepol - export a sequence of digdar radar sweeps as a bzip2-compressed WAMOS .pol file

Usage: makepol [-h] [-n N] [-i INDIR] [-o OUTDIR] [-d DECIM] [TS]

with:

    -h: show help

     N: number of consecutive sweeps to export; typically 1 + 2^m; default: 129

 INDIR: folder containing the .dat or .dat.gz sweep files; default: . (current directory)

OUTDIR: folder in which to write the .pol.bz2 file; default: . (current directory)

 DECIM: decimation factor.  If specified and > 1, then only the last of each DECIM consecutive
        samples is used.  Default: 1.

    TS: timestamp selector; this is a string matching any identifiable portion of a timestamp of
        the form YYYY-MM-DDTHH-MM-SS, e.g. "T03-45" or "02-01T".

The sweeps exported are the first N in DIR which match TS.  If TS is not
specified, the first N sweeps in DIR are used.  Sweeps are ordered by timestamp.
')
}

ARGV = commandArgs(TRUE)
ARGC = length(ARGV)
N = 129
OUTDIR = INDIR = "."
DECIM = 1
TS = NULL

doUsage = FALSE
i = 1
while( i <= length(ARGV)) {
    if (ARGV[i] == "-h") {
        doUsage = TRUE
        i = length(ARGV)
    } else if (ARGV[i] == "-n") {
        if (i < ARGC) {
            N = as.integer(ARGV[i + 1])
            i = i + 1
        } else {
            doUsage = TRUE
        }
    } else if (ARGV[i] == "-i") {
        if (i < ARGC) {
            INDIR = ARGV[i + 1]
            i = i + 1
        } else {
            doUsage = TRUE
        }
    } else if (ARGV[i] == "-o") {
        if (i < ARGC) {
            OUTDIR = ARGV[i + 1]
            i = i + 1
        } else {
            doUsage = TRUE
        }
    } else if (ARGV[i] == "-D") {
        if (i < ARGC) {
            DECIM = as.integer(ARGV[i + 1])
            if (is.na(DECIM))
                doUsage = TRUE
            i = i + 1
        } else {
            doUsage = TRUE
        }
    } else if (grepl("[-0-9T]+", ARGV[i])) {
        TS = paste0(".*", ARGV[i], ".*")
    } else {
        doUsage = TRUE
    }
    i = i + 1
}

if (doUsage) {
    usage()
    q("no")
}

suppressWarnings(suppressMessages(library(flow)))

allFiles = dir(INDIR, full.names=TRUE)
first = grep(pattern=TS, allFiles, perl=TRUE)
if (length(first) >= 1) {
    files = head(allFiles[(-1):(first[1]-1)], N)
    if (length(files) < N) {
        stop("Not enough files in ", INDIR, ":", "Only found ", length(files), " starting at match ", files[1])
    }
} else if (length(first) == 0){
    stop("No files matching ", TS, " in ", INDIR)
}

## read sweeps
sweeps = lapply(files, getSweepDigdar)

## get depths at each frame

depth = getDepth(sapply(sweeps, function(n) attr(n, "radar.meta")$ts0))

## export as Wamos file
outname = exportWamos(sweeps, path=OUTDIR, depths=depth, nACP=450, decim=DECIM)

## compress file; copy to FORCE workstation; delete
system(paste("bzip2 -9", outname))
cat(outname, "\n")
